Zauberliste = {
        "Adamantium Erzstruktur"    : ("kl","ff","ko"),
        "Adlerauge Luchsenohr"      : ("kl","in","ff"),
        "Armatrutz"                 : ("in","ge","ko"),
        "Attributo"                 : ("kl","ch"),
        "Balsam Salabunde"          : ("kl","in","ch"),
        "Blick in die Gedanken"     : ("kl","kl","ch"),
        "Blitz dich find"           : ("kl","in","ge"),
        "Corpofrigo Kälteschock"    : ("ch","ge","ko"),
        "Custodosigil Diebesbann"   : ("kl","ff","ff"),
        "Eisenrost und Patina"      : ("kl","ch","ge"),
        "Flim Flam Funkel"          : ("kl","kl","ff"),
        "Fortifex arkane Wand"      : ("in","ko","kk"),
        "Fulminictus Donnerkeil"    : ("in","ge","ko"),
        "Gardianum Zauberschild"    : ("kl","in","ko"),
        "Ignifaxius Flammenstrahl"  : ("kl","ff","ko"),
        "Ignisphaero Feuerball"     : ("mu","in","ko"),
        "Invercano Spiegeltrick"    : ("mu","in","ff"),
        "Odem Arcanum"              : ("kl","in","in"),
        "Paralysis starr wie Stein" : ("in","ch","kk"),
        "Plumbumbarum schwerer Arm" : ("ch","ge","kk"),
        "Psychostabilis"            : ("mu","kl","ko"),
        "Respondami"                : ("mu","in","ch")}
